name:                servant-poc-api
version:             0.0.1.0
github:              "barambani/servant-poc-api"
license:             MIT
author:              "barambani"
maintainer:          "example@example.com"
copyright:           "2019 barambani"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/barambani/servant-poc-api#readme>

dependencies:
- base >= 4.7 && < 5
- text
- envy
- mtl
- aeson
- servant-server
- wai
- warp
- warp-tls

library:
  source-dirs: src

executables:
  servant-poc-api-service:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-poc-api

tests:
  servant-poc-api-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-poc-api
    - hspec
